sudo: required

jobs:
  include:
  - stage: Testing
    script:
    - sh ./scripts/run-test-in-docker.sh || travis_terminate 1
  - stage: Build and publish image
    if: branch = master
    script:
    - sh ./scripts/build-and-publish-docker-image.sh || travis_terminate 1
  - stage: Publish in npm
    if: branch = master
    script:
      - sh ./scripts/publish-in-npm.sh || travis_terminate 1
